spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: users

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
      refresh-token:
        expiration: 60480000