spring:
  cloud:
    function:
      definition: orderSupplier;stockEventConsumer;orderSupplierToPayment
    stream:
      bindings:
        orderSupplier-out-0:
          destination: order-event
          group: order-group
        stockEventConsumer-in-0:
          destination: stock-event
          group: stock-group
        orderSupplierToPayment-out-0:
          destination: order-payment-event
          group: order-payment-group
