global:
  imageRepository: ghcr.io/your-org
  imageTag: latest

api-gateway:
  replicaCount: 1
users:
  replicaCount: 1
products:
  replicaCount: 1
order:
  replicaCount: 1
payment:
  replicaCount: 1
config-server:
  replicaCount: 1
eureka-server:
  replicaCount: 1